name: Convox Build
description: Build a Convox app
author: Convox
inputs:
  rack:
    description: Convox Rack name
    required: true
  app:
    description: Convox app name
    required: true
  description:
    description: Convox build description
    required: false
  cached:
    description: Whether to utilise the docker cache during the build
    required: false
    default: true
outputs:
  release:
    description: Release ID of the created build
runs:
  using: docker
  image: Dockerfile
